authors: [ eccentric_nz ]
main: me.eccentric_nz.tardisshopdoor.TardisShopDoorPlugin
name: TARDISShopDoor
description: Provides a pair of doors to teleport in and out of a TARDIS Shop
version: ${project.version}
api-version: 1.17
load: POSTWORLD
depend: [ TARDIS ]
website: http://tardisjenkins.duckdns.org:8080/job/TARDISShopDoor/
dev-url: https://github.com/eccentricdevotion/TARDISShopDoor/
url: http://eccentricdevotion.github.io/TARDIS/
permissions:
  tardis.shopdoor:
    description: Allow players to add and remove TARDIS Shop Doors.
    default: op
  tardis.shop:
    description: Allow players to use TARDIS Shop Doors.
    default: op
commands:
  tardisshopdoor:
    aliases: [ tsd ]
    usage: /<command> [name]
    description: Set or remove a pair of TARDIS Shop Doors
    permission: tardis.shopdoor
    permission-message: You don't have the permission <permission> to use this command
