author: eccentric_nz
description: Provides a pair of doors to teleport in and out of a TARDIS Shop
main: me.eccentric_nz.tardisshopdoor.TardisShopDoor
name: TARDISShopDoor
startup: postworld
softdepend: [TARDIS]
version: '1.0'
permissions:
    tardis.shopdoor:
        description: Allow players to add and remove TARDIS Shop Doors.
        default: op
    tardis.shop:
        description: Allow players to use TARDIS Shop Doors.
        default: op
commands:
    tsd:
        usage: /<command> [name]
        description: Set or remove a pair of TARDIS Shop Doors
        permission: tardis.shopdoor
        permission-message: You don't have the permission <permission> to use this command